networks:
  microblog-net:
    external: true

services:
  posts-service:
    build: .
    container_name: posts-service
    ports:
      - "8082:8080"
    networks:
      - microblog-net
    environment:
      CASSANDRA_CONTACT_POINTS: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE_NAME: posts_keyspace
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
