networks:
  microblog-net:
    name: microblog-net
    driver: bridge
    # external: true

services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - microblog-net
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis
    networks:
      - microblog-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  cassandra:
    image: cassandra:5
    container_name: cassandra
    networks:
      - microblog-net
    environment:
      CASSANDRA_CLUSTER_NAME: PostsCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    networks:
      - microblog-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    networks:
      - microblog-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-data:
  redis-data:
  cassandra-data:
